name: Installer Tests

on:
  pull_request:
    paths-ignore:
      - 'dependabot/**'
      - 'README.md'
  push:
    branches-ignore:
      - 'automated/extension_update'
      - 'automated/extension_update_tmp'
      - 'automated/dashboard_update'
      - 'automated/dashboard_update_tmp'
    paths-ignore:
      - 'dependabot/**'
      - 'README.md'

jobs:
  installer-ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./test-scripts/ballerina-test-automation/installer-test
      run: .././gradlew build --stacktrace -scan --console=plain --no-daemon
  installer-macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./test-scripts/ballerina-test-automation/installer-test
      run: .././gradlew build --stacktrace -scan --console=plain --no-daemon
  update-tool-ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./test-scripts/ballerina-test-automation/update-tool-test
      run: .././gradlew build --stacktrace -scan --console=plain --no-daemon
  update-tool-macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./test-scripts/ballerina-test-automation/update-tool-test
      run: .././gradlew build --stacktrace -scan --console=plain --no-daemon
  # windows-build:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up JDK 1.8
  #     uses: actions/setup-java@v1
  #     with:
  #       java-version: 1.8
  #   - name: Disable Firewall
  #     run: netsh advfirewall set allprofiles state off
  #   - name: Build with Gradle
  #     working-directory: ./test-scripts/ballerina-test-automation
  #     run: ./gradlew.bat build --stacktrace -scan --console=plain --no-daemon
